cpus: '4'
ram: '65536'
disk2_size: '500'
disk2: '/dev/sdb'
disk2_part: '/dev/sdb1'
orchestrator: kubernetes # or swarm

#
# the following data structures are specific to VMWare VMs and are used as such by the ansible module vmware_guest 
#
networks:
  - name: '{{ vm_portgroup }}'
    ip:  "{{ ip_addr | ipaddr('address') }}"
    netmask: "{{ ip_addr | ipaddr('netmask') }}"
    gateway: "{{ gateway }}"
#  - name: 'dpgISCSI'
#    ip:  "{{ iscsi_addr | ipaddr('address') }}"
#    netmask: "{{ iscsi_addr | ipaddr('netmask') }}"

disks_specs:
  - size_gb:  '{{ disk1_size }}'
    type: thin
    datastore: "{{ datastores | random }}"
  - size_gb: '{{ disk2_size }}'
    type: thin
    datastore: "{{ datastores | random }}"


