---
#
# find first valid ucp server
#
#   sets ucp_instance to the name of the first instance found
#   sets ucp_instance to ".none." if no instance was found
#


- name: "Find UCP: Init"
  set_fact:
    checks:
      status: -1


- name: check
  uri:
    url: "https://{{ item }}.{{ domain_name }}/auth/login"
    headers:
      Content-Type: application/json
    method: POST
    status_code: 200,500
    body_format: json
    validate_certs: no
    body: '{"username":"{{ ucp_username }}","password":"{{ ucp_password }}"}'
  delegate_to: localhost
  register: checks
  failed_when: false
  changed_when: false
  when: checks.status !=200 and checks.status != 500 
  with_items: "{{ ping_servers }}"
  no_log: yes

- set_fact: ucp_instance=".none."
- name: set ucp_instance
  set_fact: ucp_instance={{ item.item }}
  when: "'status' in item and item.status == 200"
  with_items: "{{ checks.results }}"
  no_log: yes
