baseurl: /Docker-Synergy
title: [Docker CaaS on HPE Synergy]
description: [HPE Reference Configuration for Docker Containers as a Service on HPE Synergy Composable Infrastructure]
theme: jekyll-theme-slate

