###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- name: Persistent Storage for Docker Linux (VMs)
  hosts: docker:&linux_box:&vms
  gather_facts: false
  become_user: root
  become: true

  environment:
    - "{{ env }}"

  tasks:

    - name: Check if vsphere plugin is installed
      shell: docker plugin ls | grep vsphere | wc -l
      changed_when: false
      register: vsphere_installed

    - name: Install vsphere plugin
      command: docker plugin install --grant-all-permissions --alias vsphere vmware/vsphere-storage-for-docker:{{ vsphere_plugin_version }}
      when: vsphere_installed.stdout == "0"

#####################################################################
#
# Play 2: Install vSphere plugin on Windows workers (VMware)
#
#####################################################################
- name: Persistent Storage for Docker Windows (VMs)
  hosts: docker:&windows_box:&vms
  gather_facts: false
  connection: local
  user: remote
  become: false

  tasks:

    - name: Is vSphere Plugin Installed
      win_service:
        name: vdvs
      register: vdvs_svc

    - block:

      - name: Download vSphere Docker Volume Service Installer
        win_get_url:
          url: "{{ windows_vdvs_ps }}"
          proxy_url: "{{ proxy_url }}"
          dest: "{{ windows_vdvs_directory }}install-vdvs.ps1"
        vars:
          proxy_url: "{% if env.http_proxy is defined %}{{ env.http_proxy }}{% endif %}"

      - name: Install Windows vSphere Docker Volume Service
        win_shell: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          .\install-vdvs.ps1 {{ windows_vdvs_path }}_{{ windows_vdvs_version }}.zip
        args:
          chdir: "{{ windows_vdvs_directory }}"

      - name: Configure Windows vSphere Docker Volume Service
        win_service:
          name: vdvs
          start_mode: auto
          state: started

      # Only install the plugin if it is not already installed
      when: not vdvs_svc.exists


- name: Persistent Storage for Docker Linux (Bare metal)
  hosts: docker:&linux_box:&bms
  gather_facts: false
  connection: local
  user: remote
  become: false

  tasks:
    - debug:
        msg: "not implement" 
        verbosity: 1

- name: Persistent Storage for Docker Windows (Bare metal)
  hosts: docker:&windows_box:&bms
  gather_facts: false
  connection: local
  user: remote
  become: false

  tasks:
    - debug:
        msg: "not implemented" 
        verbosity: 1

